# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/27379/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-27100-LAPTOP-N8Q4I7FI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/ADC/ADC.cache/wt [current_project]
set_property parent.project_path D:/Vivado/ADC/ADC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/ADC/ADC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/hdl/adc_wrapper.v
add_files D:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/adc.bd
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_microblaze_0_1/adc_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_microblaze_0_1/adc_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_microblaze_0_1/adc_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_axi_uartlite_0_1/adc_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_axi_uartlite_0_1/adc_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_axi_uartlite_0_1/adc_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_dlmb_v10_1/adc_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_dlmb_v10_1/adc_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_ilmb_v10_1/adc_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_ilmb_v10_1/adc_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_dlmb_bram_if_cntlr_1/adc_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_ilmb_bram_if_cntlr_1/adc_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_lmb_bram_1/adc_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_mdm_1_1/adc_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_mdm_1_1/adc_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_clk_wiz_1_1/adc_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_clk_wiz_1_1/adc_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_clk_wiz_1_1/adc_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_rst_clk_wiz_1_100M_1/adc_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_rst_clk_wiz_1_100M_1/adc_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_rst_clk_wiz_1_100M_1/adc_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_xbar_1/adc_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_xadc_wiz_0_1/adc_xadc_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/ip/adc_xadc_wiz_0_1/adc_xadc_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all D:/Vivado/ADC/ADC.srcs/sources_1/bd/adc/adc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/ADC/ADC.srcs/constrs_1/new/test1.xdc
set_property used_in_implementation false [get_files D:/Vivado/ADC/ADC.srcs/constrs_1/new/test1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top adc_wrapper -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file adc_wrapper_utilization_synth.rpt -pb adc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
