# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test1.xdc

# Block Designs: bd/adc/adc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc || ORIG_REF_NAME==adc} -quiet] -quiet

# IP: bd/adc/ip/adc_microblaze_0_1/adc_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_microblaze_0_1 || ORIG_REF_NAME==adc_microblaze_0_1} -quiet] -quiet

# IP: bd/adc/ip/adc_axi_uartlite_0_1/adc_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_axi_uartlite_0_1 || ORIG_REF_NAME==adc_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/adc/ip/adc_dlmb_v10_1/adc_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_dlmb_v10_1 || ORIG_REF_NAME==adc_dlmb_v10_1} -quiet] -quiet

# IP: bd/adc/ip/adc_ilmb_v10_1/adc_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_ilmb_v10_1 || ORIG_REF_NAME==adc_ilmb_v10_1} -quiet] -quiet

# IP: bd/adc/ip/adc_dlmb_bram_if_cntlr_1/adc_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==adc_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/adc/ip/adc_ilmb_bram_if_cntlr_1/adc_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==adc_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/adc/ip/adc_lmb_bram_1/adc_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_lmb_bram_1 || ORIG_REF_NAME==adc_lmb_bram_1} -quiet] -quiet

# IP: bd/adc/ip/adc_mdm_1_1/adc_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_mdm_1_1 || ORIG_REF_NAME==adc_mdm_1_1} -quiet] -quiet

# IP: bd/adc/ip/adc_clk_wiz_1_1/adc_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_clk_wiz_1_1 || ORIG_REF_NAME==adc_clk_wiz_1_1} -quiet] -quiet

# IP: bd/adc/ip/adc_rst_clk_wiz_1_100M_1/adc_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==adc_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/adc/ip/adc_xbar_1/adc_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_xbar_1 || ORIG_REF_NAME==adc_xbar_1} -quiet] -quiet

# IP: bd/adc/ip/adc_microblaze_0_axi_periph_1/adc_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_microblaze_0_axi_periph_1 || ORIG_REF_NAME==adc_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/adc/ip/adc_xadc_wiz_0_1/adc_xadc_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_xadc_wiz_0_1 || ORIG_REF_NAME==adc_xadc_wiz_0_1} -quiet] -quiet

# XDC: bd/adc/adc_ooc.xdc
